-- ============================================================
-- DATA INSERTION: Professors
-- Note:
-- we took the first name inital and full last name to create the emails
-- if that is the real email, that was created unintentionally
-- ============================================================
INSERT INTO Professors (EmployeeID, FirstName, LastName, Email, MajorOfInstruction)
VALUES
(1, 'Alaron', 'Lewis', 'aLewis@uw.edu', 'B BIO'),
(2, 'Douglas', 'Wacker', 'dWacker@uw.edu', 'B BIO'),
(3, 'Jesse', 'Zaneveld', 'jZaneveld@uw.edu', 'B BIO'),
(4, 'Michele', 'B. Price', 'mPrice@uw.edu', 'B BIO'),
(5, 'Jeffrey', 'Jensen', 'jJensen@uw.edu', 'B BIO'),
(6, 'Elizabeth', 'Ostrowski', 'eOstrowski@uw.edu', 'B BIO'),
(7, 'Peter', 'Anderson', 'pAnderson@uw.edu', 'B CHEM'),
(8, 'Han-Wei', 'Shih', 'hShih@uw.edu', 'B BIO'),
(9, 'Salwa', 'Al-Noori', 'aAl-Noori@uw.edu', 'B CORE'),
(10, 'Ian', 'Gillis', 'iGillis@uw.edu', 'B BIO'),
(11, 'Tim', 'Cooper', 'tCopper@uw.edu', 'B BIO'),
(12, 'Michael', 'Stiber', 'mStiber@uw.edu', 'CSS'),
(13, 'Dawn-Marie', 'Oliver', 'dmOliver@uw.edu', 'CSS'),
(14, 'Douglas', 'M. Pyle', 'dPyle@uw.edu', 'CSS'),
(15, 'Johnny', 'Lin', 'jLin@uw.edu', 'CSS'),
(16, 'Katie', 'Ewing', 'kEwing@uw.edu', 'CSS'),
(17, 'Morteza', 'Chini', 'mChini@uw.edu', 'CSS'),
(18, 'Peng', 'Du', 'pDu@uw.edu', 'CSS'),
(19, 'DAVID', 'NIXON', 'dNixon@uw.edu', 'CSS'),
(20, 'Jeff', 'Stride', 'jStride@uw.edu', 'CSS'),
(21, 'Dharma', 'Dailey', 'dDailey@uw.edu', 'CSS'),
(22, 'Nancy', 'L. Kool', 'nKool@uw.edu', 'CSS'),
(23, 'Carol', 'A Shaw', 'cShaw@uw.edu', 'CSS'),
(24, 'Ahmed', 'Awad', 'aAwd@uw.edu', 'CSS'),
(25, 'Sanjay', 'Joshi', 'sJoshi@uw.edu', 'CSS'),
(26, 'Geetha', 'Thamilarasu', 'gThamilarasu@uw.edu', 'CSS'),
(27, 'Eyal', 'Arian', 'eArian@uw.edu', 'CSS'),
(28, 'Clark', 'Olson', 'cOlson@uw.edu', 'CSS'),
(29, 'Murat', 'Seckin Ayhan', 'mSeckin-Ayhan@uw.edu', 'CSS'),
(30, 'Joanna', 'Wang', 'jWang@uw.edu', 'CSS'),
(31, 'Neelakantan', 'Kartha', 'nKartha@uw.edu', 'CSS'),
(32, 'Shaun', 'Stangler', 'sStangler@uw.edu', 'CSS'),
(33, 'Eric', 'Reel', 'eReel@uw.edu', 'CSS'),
(34, 'Yusuf', 'Pisan', 'yPisan@uw.edu', 'CSS'),
(35, 'Mia', 'Champion', 'mChampion@uw.edu', 'CSS'),
(36, 'Kaylea', 'Champion', 'kChampion@uw.edu', 'CSS'),
(37, 'Jeffrey', 'Kim', 'jKim@uw.edu', 'CSS'),
(38, 'Himanshu', 'Zade', 'hZade@uw.edu', 'CSS'),
(39, 'Arkady', 'Retik', 'aRetik@uw.edu', 'CSS'),
(40, 'William', 'Lidster', 'wLidster@uw.edu', 'CSS'),
(41, 'Munehiro', 'Fukuda', 'mFukuda@uw.edu', 'CSS'),
(42, 'STEVE', 'DAME', 'sDame@uw.edu', 'CSS'),
(43, 'Irena', 'Atov', 'iAtov@uw.edu', 'CSS'),
(44, 'John', 'Chenault', 'jChenault@uw.edu', 'CSS'),
(45, 'Praveen', 'Bantwal', 'pBantwal@uw.edu', 'CSS'),
(46, 'Dharmesh', 'Kumar', 'dKumar@uw.edu', 'CSS'),
(47, 'Wooyoung', 'Kim', 'wKim@uw.edu', 'CSS'),
(48, 'Muntasir', 'Raihan Rahman', 'mRihan-Rahman@uw.edu', 'CSS'),
(49, 'Marc', 'J. DupuisSteven Oscar Melnikoff', 'mDOM@uw.edu', 'CSS'),
(50, 'Laurie', 'Anderson', 'lAnderson@uw.edu', 'CSS'),
(51, 'Min', 'Chen', 'mChen@uw.edu', 'CSS'),
(52, 'Eric', 'Brechner', 'eBrechner@uw.edu', 'CSS'),
(53, 'Marc', 'J. Dupuis', 'mDupuis@uw.edu', 'CSS'),
(54, 'Erika', 'Parsons', 'eParsons@uw.edu', 'CSS'),
(55, 'Kelvin', 'Sung', 'kSung@uw.edu', 'CSS'),
(56, 'Chris', 'Phillips', 'cPhillips@uw.edu', 'CSS'),
(57, 'Brent', 'J Lagesse', 'bLagesse@uw.edu', 'CSS'),
(58, 'Bill', 'Erdly', 'bErdly@uw.edu', 'CSS'),
(59, 'Abdlmagid', 'Basere', 'aBasere@uw.edu', 'B EE'),
(60, 'Reshma', 'Chandrasekharan', 'rChandrasekharan@uw.edu', 'B EE'),
(61, 'Mahmoud', 'Ghofrani', 'mghofrani@uw.edu', 'B EE'),
(62, 'Joseph', 'Decuir', 'jdecuir@uw.edu', 'B EE'),
(63, 'Walter', 'Charczenko', 'wcharczenko@uw.edu', 'B EE'),
(64, 'Madhava', 'Sarma Vemuri', 'msv@uw.edu', 'B EE'),
(65, 'Harry', 'Aintablian', 'haintablian@uw.edu', 'B EE'),
(66, 'Konpal', 'Shaukat Ali', 'ksali@uw.edu', 'B EE'),
(67, 'Kyoung', 'Tae Kim', 'kkim@uw.edu', 'B EE'),
(68, 'Narges', 'Masoumi', 'nmasoumi@uw.edu', 'B ME'),
(69, 'Imen', 'Hannachi', 'ihannachi@uw.edu', 'B ENGR'),
(70, 'Debby', 'Williams', 'dwilliams@uw.edu', 'B MATH'),
(71, 'Bilin', 'Z Stiber', 'bstiber@uw.edu', 'B MATH'),
(72, 'Baaska', 'Anderson', 'banderson@uw.edu', 'B MATH'),
(73, 'Jong', 'Yoon', 'jyoon@uw.edu', 'B ME'),
(74, 'Shima', 'Abadi', 'sabadi@uw.edu', 'B ME'),
(75, 'Bill', 'Anderson', 'banderson@uw.edu', 'B ME'),
(76, 'Nathan', 'Mead', 'nmead@uw.edu', 'B ME'),
(77, 'Miguel', 'Balzan', 'mbalzan@uw.edu', 'B ME'),
(78, 'Emily', 'Gismervig', 'egismervig@uw.edu', 'STMATH'),
(79, 'Marina', 'Moraiti', 'mmoraiti@uw.edu', 'STMATH'),
(80, 'Dale', 'Hockstra', 'dhockstra@uw.edu', 'STMATH'),
(81, 'Mufid', 'Abudiab', 'mabudiab@uw.edu', 'STMATH'),
(82, 'Elizabeth', 'Field', 'efield@uw.edu', 'STMATH'),
(83, 'Shubha', 'Rajopadhye', 'srajopadhye@uw.edu', 'STMATH'),
(84, 'Ariana', 'F. Dundon', 'adundon@uw.edu', 'STMATH'),
(85, 'Alexandria', 'Theakston Musselman', 'atm@uw.edu', 'STMATH'),
(86, 'Alexandre', 'Barchechat', 'abarchechat@uw.edu', 'STMATH'),
(87, 'Clark', 'Musselman', 'cmusselman@uw.edu', 'STMATH'),
(88, 'Pietro', 'Paparella', 'ppaparella@uw.edu', 'STMATH'),
(89, 'Andrew', 'Abian', 'aabian@uw.edu', 'STMATH'),
(90, 'Antonio', 'Kirson', 'akirson@uw.edu', 'STMATH'),
(91, 'Casey', 'Mann', 'cmann@uw.edu', 'STMATH'),
(92, 'Thomas', 'Humphries', 'thumphries@uw.edu', 'STMATH'),
(93, 'Milagros', 'Loreto', 'mloreto@uw.edu', 'STMATH'),
(94, 'Charity', 'Lovitt', 'clovitt@uw.edu', 'B CHEM'),
(95, 'David', 'Sommerfeld', 'dsommerfeld@uw.edu', 'B CHEM'),
(96, 'Murali', 'Thimmaiah', 'mthimmaiah@uw.edu', 'B CHEM'),
(97, 'Scott', 'Shippy', 'sshippy@uw.edu', 'B CHEM'),
(98, 'Brandon', 'D Finley', 'bfinley@uw.edu', 'B CHEM'),
(99, 'Khushroo', 'P. Daruwala', 'kdaruwala@uw.edu', 'B CHEM'),
(100, 'Dan', 'Jaffe', 'djaffe@uw.edu', 'B CHEM'),
(101, 'Hyung', 'J Kim', 'hkim@uw.edu', 'B CHEM'),
(102, 'Matthew', 'Gliboff', 'mgliboff@uw.edu', 'B PHYS'),
(103, 'Jaimy', 'Tomlinson', 'jtomlinson@uw.edu', 'B PHYS'),
(104, 'Alanna', 'Pawlak', 'apawlak@uw.edu', 'B PHYS'),
(105, 'Benjamin', 'N. Grossmann', 'bgrossmann@uw.edu', 'B PHYS'),
(106, 'Paola', 'Rodriguez Hidalgo', 'prh@uw.edu', 'B PHYS'),
(107, 'Joshua', 'J. Kas', 'jkas@uw.edu', 'B PHYS'),
(108, 'RACHEL', 'E. SCHERR', 'rscherr@uw.edu', 'B PHYS'),
(109, 'Subramanian', 'Ramachandran', 'sramachandran@uw.edu', 'B CORE'),
(110, 'Eric', 'P Salathe', 'esalathe@uw.edu', 'B PHYS'),
(111, 'Heather', 'Galindo', 'hgalindo@uw.edu', 'BST'),
(112, 'Murgie', 'Krishnan', 'mkrishnan@uw.edu', 'B BUS'),
(113, 'Kara', 'Wells', 'kwells@uw.edu', 'B BUS'),
(114, 'Rajib', 'Doogar', 'rdoogar@uw.edu', 'B BUS'),
(115, 'Anurag', 'Tewari', 'atewari@uw.edu', 'B BUS'),
(116, 'Daniel', 'Nielubowicz', 'dnielubowicz@uw.edu', 'B BUS'),
(117, 'Codrin', 'Nedita', 'cnedita@uw.edu', 'B BUS'),
(118, 'S', 'Charusheela', 'scharusheela@uw.edu', 'BIS'),
(119, 'Elizabeth', 'H Follmer', 'efollmer@uw.edu', 'B BUS'),
(120, 'Vivian', 'Lu Xiao', 'vlx@uw.edu', 'B BUS'),
(121, 'Camelia', 'Bejan', 'cbejan@uw.edu', 'B BUS'),
(122, 'Kivalina', 'Grove', 'kgrove@uw.edu', 'B BUS'),
(123, 'Ying', 'Yang', 'yyang@uw.edu', 'B BUS'),
(124, 'Joey', 'Choi', 'jchoi@uw.edu', 'B BUS'),
(125, 'Solmaz', 'Batebi', 'sbatebi@uw.edu', 'B BUS'),
(126, 'Lakshmana', 'K. Krishna Moorthy', 'lkm@uw.edu', 'B BUS'),
(127, 'Wei', 'Li', 'wli@uw.edu', 'B BUS'),
(128, 'Ceri', 'Nishihara', 'cnishihara@uw.edu', 'B BUS'),
(129, 'Andrea', 'Anthony', 'aanthony@uw.edu', 'B BUS'),
(130, 'Brandon', 'Edward Fleming', 'bef@uw.edu', 'B BUS'),
(131, 'David', 'S. Shaw', 'dshaw@uw.edu', 'B BUS'),
(132, 'P.V.', '''Sundar'' Balakrishnan', 'sbalakrishnan@uw.edu', 'B BUS'),
(133, 'Juan', 'Camilo Gomez', 'jcgomez@uw.edu', 'B BUS'),
(134, 'Alejandro', 'Francetich', 'afrancetich@uw.edu', 'B BECN'),
(135, 'Katja', 'A Koehnlein', 'kkoehnlein@uw.edu', 'B EDUC'),
(136, 'frederick', 'Douglass h alcorn', 'falcorn@uw.edu', 'B EDUC'),
(137, 'Natasha', 'H. Merchant', 'nmerchant@uw.edu', 'B EDUC'),
(138, 'Sooz', 'Desha Stahl', 'sds@uw.edu', 'B EDUC'),
(139, 'Todd', 'Allan Martinez-Simmons', 'tams@uw.edu', 'B EDUC'),
(140, 'Jeff', 'Stone', 'jstone@uw.edu', 'B EDUC'),
(141, 'Third', 'Andresen', 'tandresen@uw.edu', 'B EDUC'),
(142, 'Jed', 'Murr', 'jmurr@uw.edu', 'BIS'),
(143, 'Sarita', 'Shukla', 'sshukla@uw.edu', 'B EDUC'),
(144, 'Derya', 'Baykent', 'dbaykent@uw.edu', 'B EDUC'),
(145, 'Katie', 'Mathew', 'kmathew@uw.edu', 'B EDUC'),
(146, 'Jason', 'M Naranjo', 'jnaranjo@uw.edu', 'B EDUC'),
(147, 'Nathanie', 'A Lee', 'nlee@uw.edu', 'B EDUC'),
(148, 'Alexandra', 'L. Goodell', 'agoodell@uw.edu', 'B EDUC'),
(149, 'Jamie', 'Cho', 'jcho@uw.edu', 'B EDUC'),
(150, 'Allison', 'Beth Hintz', 'abh@uw.edu', 'B EDUC'),
(151, 'Antony', 'Smith', 'asmith@uw.edu', 'B EDUC'),
(152, 'sj', 'Miller', 'smiller@uw.edu', 'B EDUC'),
(153, 'Christy', 'Johnson', 'cjohnson@uw.edu', 'B CORE'),
(154, 'Gavin', 'Doyle', 'gdoyle@uw.edu', 'B CORE'),
(155, 'Louise', 'Spiegler', 'lspiegler@uw.edu', 'B CORE'),
(156, 'Michael', 'StiberSalwa Al-Noori', 'msan@uw.edu', 'B CORE'),
(157, 'Nora', 'Kenworthy', 'nkenworthy@uw.edu', 'BHS'),
(158, 'Sunita', 'Iyer', 'siyer@uw.edu', 'B CORE'),
(159, 'Samuel', 'Yum', 'syum@uw.edu', 'B CORE'),
(160, 'Georgia', 'M. Roberts', 'groberts@uw.edu', 'BIS'),
(161, 'Howard', 'Hsu', 'hhsu@uw.edu', 'BISIA'),
(162, 'Suzanne', 'YatesCinnamon Hillyard', 'sych@uw.edu', 'B CORE'),
(163, 'Kristen', 'Labrecque', 'klabrecque@uw.edu', 'B CORE'),
(164, 'Cinnamon', 'Hillyard', 'chillyard@uw.edu', 'B CUSP'),
(165, 'Lupe', 'R Collins', 'lcollins@uw.edu', 'B WRIT'),
(166, 'Jessica', 'Ketcham', 'jketcham@uw.edu', 'B WRIT'),
(167, 'Silvia', 'C. Ferreira', 'sferreira@uw.edu', 'B WRIT'),
(168, 'Stephie', 'Kang', 'skang@uw.edu', 'B WRIT'),
(169, 'Jonathan', 'Rey Lee', 'jrl@uw.edu', 'B WRIT'),
(170, 'Elizabeth', 'Cole Janssen', 'ecj@uw.edu', 'B WRIT'),
(171, 'Ian', 'Porter', 'iporter@uw.edu', 'B WRIT'),
(172, 'Furkan', 'Kir', 'fkir@uw.edu', 'B WRIT'),
(173, 'Kris', 'Kellejian', 'kkellejian@uw.edu', 'BIS'),
(174, 'Hsinmei', 'Lin', 'hlin@uw.edu', 'B WRIT'),
(175, 'Jason', 'H Morse', 'jmorse@uw.edu', 'B WRIT'),
(176, 'Jessica', 'Campbell', 'jcampbell@uw.edu', 'B WRIT'),
(177, 'Neil', 'Simpkins', 'nsimpkins@uw.edu', 'B WRIT'),
(178, 'Mira', 'Shimabukuro', 'mshimabukuro@uw.edu', 'BISAES'),
(179, 'Joe', 'Milutis', 'jmilutis@uw.edu', 'BIS'),
(180, 'Jeanne', 'Heuving', 'jheuving@uw.edu', 'BCWRIT'),
(181, 'David', 'S. Goldstein', 'dgoldstein@uw.edu', 'BIS'),
(182, 'Caleb', 'Trujillo', 'ctrujillo@uw.edu', 'B DATA'),
(183, 'Gani', 'Nurmukhametov', 'gnurmukhametov@uw.edu', 'B DATA'),
(184, 'Nicole', 'Cote', 'ncote@uw.edu', 'B DATA'),
(185, 'Alex', 'Marquez', 'amarquez@uw.edu', 'BEARTH'),
(186, 'Tracy', 'A Fields', 'tfields@uw.edu', 'BEARTH'),
(187, 'Avery', 'Shinneman', 'ashinneman@uw.edu', 'BEARTH'),
(188, 'Rob', 'Turner', 'rturner@uw.edu', 'BES'),
(189, 'Becca', 'Price', 'bprice@uw.edu', 'BES'),
(190, 'Ursula', 'Valdez', 'uvaldez@uw.edu', 'BES'),
(191, 'Eric', 'A Graham', 'egraham@uw.edu', 'BIS'),
(192, 'Sara', 'Maxwell', 'smaxwell@uw.edu', 'BES'),
(193, 'Amy', 'M Lambert', 'alambert@uw.edu', 'BIS'),
(194, 'Julie', 'Shayne', 'jshayne@uw.edu', 'BISGWS'),
(195, 'dana', 'middleton', 'dmiddleton@uw.edu', 'BISIA'),
(196, 'Anida', 'Yoeu AliAmaranth BorsukNaomi Macalalad Bragin', 'yaabnmb@uw.edu', 'BISIA'),
(197, 'Masahiro', 'Sugano', 'msugano@uw.edu', 'BISMCS'),
(198, 'Carrie', 'Bodle', 'cbodle@uw.edu', 'BISIA'),
(199, 'Katharine', 'Norton', 'knorton@uw.edu', 'BISIA'),
(200, 'Amaranth', 'Borsuk', 'aborsuk@uw.edu', 'BISIA'),
(201, 'Naomi', 'Macalalad Bragin', 'nmb@uw.edu', 'BISIA'),
(202, 'gary', 'carpenter', 'gcarpenter@uw.edu', 'BISIA'),
(203, 'Sabina', 'Abd Livadariu', 'sal@uw.edu', 'BISIA'),
(204, 'Shannon', 'Cram', 'scram@uw.edu', 'BISSTS'),
(205, 'Adam', 'Romero', 'aromero@uw.edu', 'BISSTS'),
(206, 'Anida', 'Yoeu Ali', 'aya@uw.edu', 'BIS'),
(207, 'Mary', 'V. McGuire', 'mmcguire@uw.edu', 'BIS'),
(208, 'jason', 'frederick lambacher', 'jlambacher@uw.edu', 'BIS'),
(209, 'Lauren', 'S. Berliner', 'lberliner@uw.edu', 'BIS'),
(210, 'Christian', 'Anderson', 'canderson@uw.edu', 'BIS'),
(211, 'Matthew', 'Eissa Toro', 'met@uw.edu', 'BIS'),
(212, 'Anne', 'Richards', 'arichards@uw.edu', 'BIS'),
(213, 'Lauren', 'F. Lichty', 'llichty@uw.edu', 'BIS'),
(214, 'Janelle', 'M Silva', 'jsilva@uw.edu', 'BISPSY'),
(215, 'Andrew', 'D Jorgenson', 'ajorgenson@uw.edu', 'BIS'),
(216, 'Santiago', 'Lopez', 'slopez@uw.edu', 'BIS'),
(217, 'MARGARET', 'Redsteer', 'mredsteer@uw.edu', 'BIS'),
(218, 'Jennifer', 'Atkinson', 'jatkinson@uw.edu', 'BIS'),
(219, 'Alka', 'Kurian', 'akurian@uw.edu', 'BIS'),
(220, 'Melanie', 'Malone', 'mmalone@uw.edu', 'BIS'),
(221, 'William', 'Hartmann', 'whartmann@uw.edu', 'BIS'),
(222, 'Michael', 'Vallerga', 'mvallerga@uw.edu', 'BIS'),
(223, 'Jaki', 'Yi', 'jyi@uw.edu', 'BIS'),
(224, 'Kristin', 'Gustafson', 'kgustafson@uw.edu', 'BIS'),
(225, 'Raissa', 'DeSmetNhi Phuong Tran', 'dsnpt@uw.edu', 'BIS'),
(226, 'Ryan', 'Burns', 'rburns@uw.edu', 'BIS'),
(227, 'Maryam', 'S Griffin', 'mgriffin@uw.edu', 'BISLEP'),
(228, 'Susan', 'Harewood', 'sharewood@uw.edu', 'BIS'),
(229, 'Kari', 'A Lerum', 'klerum@uw.edu', 'BIS'),
(230, 'Laura', 'J Harkewicz', 'lharkewicz@uw.edu', 'BIS'),
(231, 'Veronica', 'Cassone McGowan', 'vcm@uw.edu', 'BIS'),
(232, 'Alice', 'Pedersen', 'apedersen@uw.edu', 'BIS'),
(233, 'Randy', 'Spaulding', 'rspaulding@uw.edu', 'BIS'),
(234, 'Raissa', 'DeSmetNhi Phuong Tran', 'dsnpt@uw.edu', 'BIS'),
(235, 'Garick', 'Sherburn', 'gsherburn@uw.edu', 'BISSKL'),
(236, 'Keith', 'Nitta', 'knitta@uw.edu', 'BPOLST'),
(237, 'Amoshaun', 'Toft', 'atoft@uw.edu', 'BISMCS'),
(238, 'Ron', 'Krabill', 'rkrabill@uw.edu', 'BISMCS'),
(239, 'Minda', 'J. Martin', 'mmartin@uw.edu', 'BISMCS'),
(240, 'Charles', 'R. Collins', 'ccollins@uw.edu', 'BPOLST'),
(241, 'Jin-Kyu', 'Jung', 'jjung@uw.edu', 'BPOLST'),
(242, 'Eric', 'S Anderson', 'eanderson@uw.edu', 'B HLTH'),
(243, 'Andrea', 'L Stone', 'astone@uw.edu', 'B HLTH'),
(244, 'Miryha', 'Gould Runnerstrom', 'mgr@uw.edu', 'B HLTH'),
(245, 'Cynthia', 'Karlsson', 'ckarlsson@uw.edu', 'BHS'),
(246, 'Kosuke', 'Niitsu', 'kniitsu@uw.edu', 'B HLTH'),
(247, 'Diana', 'Odland Neal', 'don@uw.edu', 'B NURS'),
(248, 'Tara', 'Goode', 'tgoode@uw.edu', 'BHS'),
(249, 'Maria', 'T. Blancas', 'mblancas@uw.edu', 'BHS'),
(250, 'Tara', 'James', 'tjames@uw.edu', 'BHS'),
(251, 'Damarys', 'Espinoza', 'despinoza@uw.edu', 'BHS'),
(252, 'Jody', 'O. Early', 'jearly@uw.edu', 'BHS'),
(253, 'Robin', 'Fenn', 'rfenn@uw.edu', 'BHS'),
(254, 'Shari', 'L. Dworkin', 'sdworkin@uw.edu', 'BHS'),
(255, 'Lisa', 'LR Howard', 'lhoward@uw.edu', 'B NURS'),
(256, 'Celia', 'Rose Gorbman', 'crg@uw.edu', 'B NURS'),
(257, 'Joanna', 'Yi', 'jyi@uw.edu', 'B NURS'),
(258, 'DEBRA', 'ANN RIDLING', 'dridling@uw.edu', 'B NURS'),
(259, 'Selina', 'Mohammed', 'smohammed@uw.edu', 'B NURS'),
(260, 'Linda', 'Eaton', 'leaton@uw.edu', 'B NURS'),
(261, 'Audrey', 'Lynn Covner', 'alc@uw.edu', 'B NURS'),
(262, 'Mabel', 'C. Ezeonwu', 'mezeonwu@uw.edu', 'B NURS'),
(263, 'Cynthia', 'Chang', 'cchang@uw.edu', 'B BIO'),
(264, 'Dana', 'Campbell', 'dcampbell@uw.edu', 'B BIO');